<?php
// prevent lauching the wizard if the config file already exists
if (file_exists('config/config.php')) {
	echo "Configuration file already exists.";
}

$ok = false;
// form submited --> create config.php
if (	isset($_POST)
	&&	isset($_POST['title']) && strlen($_POST['title'])>0
	&&	isset($_POST['database']) && strlen($_POST['database'])>0
	&&	isset($_POST['page_size']) && strlen($_POST['page_size'])>0
	) {

	$now = date('r');

	$tmp = array();
	for($i=0 ; $i<sizeof($_POST['paths']) ; $i++) {
		$tmp[] .= "'".str_replace("'","\\'",$_POST['paths'][$i])."'	=> array('label'=>'".str_replace("'","\\'",$_POST['labels'][$i])."',	'virtual'=>'".str_replace("'","\\'",$_POST['alias'][$i])."')";
	}
	$directories = join(",\n",$tmp);
	
$text = <<<EOT
<?php
# this file was generated by the wizard install on $now
define ('SONGS_PATHS',serialize(array(
	$directories
)));

define('TITLE','$_POST[title]'); // title of the application
define('DATABASE','$_POST[database]'); // path to the database
define('PAGE_SIZE',$_POST[page_size]); // default page size of search results
?>
EOT;

	// save configuration
	$config = fopen('config/config.php','w+') or die("Could not open config/config.php for writing");
	fwrite($config,$text) or die("Could not write in config/config.php");
	fclose($config);

	$ok = true;
}
?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="css/install.css">
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/install.js"></script>
</head>
<body>
<?php

if ($ok && file_exists('config/config.php')) { ?>

Configuration file has been created in <strong>'config/config.php'</strong>.<br/>
If you want do configure the application again, just remove or rename 'config/config.php'.<br/>
<br/>
Now you can build your songs database by launching the script in bin/build_database.php :
<pre>
%cd bin
%php build_database.php
</pre>

<a href="index.php">Launch the application</a>

	
<? } else { // display wizard form ?>
<h1 id="welcome">Welcome to the wizard configuration</h1>

<form id="install_form" method="POST" name="install_form" action="<?=$_SERVER['PHP_SELF']?>">

	<div class="variable">
		<label for="title">Application title</label>
		<input id="title" name="title" value="My MP3 Player" placeholder="Title..." />
	</div>

	<div class="variable">
		<label for="database">Path to database</label>
		<input id="database" name="database" value="../../databases/song.sqlite" placeholder="path" />
		<span class="check"></span>
	</div>

	<div class="variable">
		<label for="page_size">Default page size for search results</label>
		<select id="page_size" name="page_size">
			<option value="10" selected="selected">10</option>
			<option value="20">20</option>
			<option value="50">50</option>
			<option value="100">100</option>
			<option value="200">200</option>
		</select>
	</div>

	<div class="variable">
		<label>Directories to index</label>
		<ol id="directories"></ol>
		<a id="add_path_btn" class="btn btn-success btn-xs" href="#"><i class="fa fa-plus fa-lg"></i> Add path</a>
	</div>

	<div class="variable">
		<a id="save_btn" class="btn btn-success btn-sm" href="#"><i class="fa fa-save fa-lg"></i> Save configuration</a>
	</div>
</form>
<? } // end of form ?>
</body>
</html>
<? exit; ?> 